application_port: "8091"

# mysql配置文件
mysql:
  host: "127.0.0.1"   # mysql地址
  port: "3306"   # 运行端口
  username: "root" # 用户名
  password: "Or2452020438" # 密码
  database: "ChainLogix" # 数据库

email:
  username: "2476358005@qq.com" # 发送者的邮箱地址
  password: "cnjfoyucileudicd"  # 授权密码
  host: "smtp.qq.com"           # 邮件协议
  port: "587"                   # 端口号

redis:
  address: "localhost:6379" # redis客户端的地址
  password: "" # 密码
  db: 0 # 使用哪个数据库

mapApiKey: '29b5f74e7e7f47e8ef034e6cc0e8db5f'
# 25125b66d60b8e29dfdde781c72bf6cd b3234df6ac1c1ba9a52b24c3b8e656f2
# 合约地址
contract_address: "0x16488Ca4a0aF55b12Bde293eD69b7A676864948D"

alipay:
  app_id: "9021000133606417"
  k_private_key: "MIIEpAIBAAKCAQEA8IDOcmSsxLZNH6nN2YmkeAgBiemfwDzbMpT5Hhf6VdCyiRCEyEh5LVR3mgZyRn+zYpNDhlPRIFYc4fiJppYBNpnLwAusvAGa8Eg5BIrH5PyijVncvtbA1lpEgPDEOTd7QGtW2twyFev42rKNxDLkykjmSAZ8gPcs6ofSvlhQXn5utxTGMs+DKU8jJe7wwp7MNhOsfO1bvyZpwgGFgt7NQNdb3CR7H5PD0zvi21251ijm12Pq2mMtk/w8ToMSRRLUwPodp/hRZD95HjKjMtckxpxklWeP1q4Ugvns3HrVsjUO/v7Ha4rZvlh/6AqTQuGHZcmItTjyPATqFEEjK4MjiwIDAQABAoIBAQCmxGpjIDQ84zxvbEt1QOBu6v5GJ13C63ADjxF/MJlB0Ek8idvJFZgROrUEdNvgzsQQ4pS8HHqytYOpnbG1dea5ecOzE2VfqK1LWIlRAPrDafs9kMZk/n0RJd7CmjE2i6ZHcSb09CM22D3jSFTNa40CR7KG1xiWRM88gZo8qvhvzFvObEfdMfmDuLgWEGDLeqGuaaXCeRS31uMOVBl5OMc7FdtxJd4zYBRgUL/BEeaMXLk8j9aXdXx8jJLiWuzN8bSTtuCpN6iIHKDAaR5ydcj8Jvn9u1kQZZIZrRxq7dwCbTX7cOhTNLSUllUjIUNp8C+2rvKYUhm2v1RT8zL+mplhAoGBAPq5fOHe/BReQ3G6xFrUbY3gq9Qn0cF0q+QhTeoGXvR6Cchu3xchaqptHWLFVcpMDRTeAvA+e7ZSt2d0N8Mf/R073GQbjEFlSx/3wWvaxBi47avHY2l4itq5bc/YY7JJqChHQsMTUpDVXyUZ8xPuRZl1vIc1wncLu2spU4mKKmafAoGBAPWQQvlMLUHrgOOydXhSlMQnDv7dFHESjaiuvprNieqlbNlaYX5CcidBLku1ZjHAfEak2cMGAz/m4dLacRRfkSPC+Q+lv2ctowVdo1vq95rQJPyabhue7aZyXuZfZ5xGZ9q0LjG0Dzr/8Qe9RLrSnf5CFEymfIf7k3R9Jh6Q7veVAoGAD7k+ObQQPv7CYAmEcuXLkRA79mwg3W8BsKbeCgUoQ1C7+FPrrbmsxM9e/mi9vpgSYfKiYIqqm36IffZt4NDKwOCWK7kGjLtbgL+645auoZZHYXR5qY2jt5/VYSmC5xVzdEMzzqQRk3+uHdeIxQE2YC9gCWK3tVuI/2lyEbgWfKUCgYBuA5iNubwY6VpQKJaKNm0hx+Hm+sL6uXYvmUIZdnYQYtZ2NhCxkTE1NvV3w6gqJ/NFbvuEbQAts9F+NpEssHgEzofoo7gxkHeVotLaDlWpzRCU/tbPlw8fX+P2T83KbJyAlfKQH/wm0Z15eyj8jflsfMw9XuUxwtrX+G2IiiQVVQKBgQCqRlBWlBkBUtH3AU7NI8/+RGh7ZFj1gRmFIcW6owhLpbBuJKlsX4pW7m7sTpqFcy131v9rc0lhmRaYJ9rPcjhMpG842iM10XlN7fegAbch+U8VaG9ybLgFPTlAaAeKn05NXSTNSoDdOudGgBrgp53hz69H+CQZJxN/EzrW+kS7Pg=="
  alipay_public_key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkw1bmttaYp/gUln/e2p5t2HSVNxXcZX4MA9lA+r53ZZkKe4m2kN3Io8G5uPWq3ExfpLAO6bDEK3fjxCPmHLf8PZ7w/Sr1Azb2DlCCxZ2s15F3QvpBf/f2vigyF7pHX/ZxmmscW782QvlueBB08fZLeIUIGXkRFiE9cWlm0a6yf8HY390czGTI8wt3G3D7Q27P+0Xdfmfyzt++QAkbpT9OuvqSs6i+jbCXSGItdmgXPx4bJrrmFRZHAS/PYEAY/lrkgBHNqcE5xhh8R1mQdioqpX26uzzhuEy/E3iTVHYBgm1a2h1vfbCxjSBNS6VFAy7jQjuMdC4i/LGsO71UYAEHQIDAQAB"
  k_server_domain: "http://127.0.0.1:8091"  # 支付重定向域名