application_port: "8091"

# mysql配置文件
mysql:
  host: "127.0.0.1"   # mysql地址
  port: "3306"   # 运行端口
  username: "root" # 用户名
  password: "Or2452020438" # 密码
  database: "ChainLogix" # 数据库

email:
  username: "" # 发送者的邮箱地址
  password: ""  # 授权密码
  host: ""           # 邮件协议
  port: "587"                   # 端口号

redis:
  address: "localhost:6379" # redis客户端的地址
  password: "" # 密码
  db: 0 # 使用哪个数据库

mapApiKey: ''
# 25125b66d60b8e29dfdde781c72bf6cd b3234df6ac1c1ba9a52b24c3b8e656f2
# 合约地址
contract_address: "0x16488Ca4a0aF55b12Bde293eD69b7A676864948D"

alipay:
  app_id: ""
  k_private_key: ""
  alipay_public_key: ""
  k_server_domain: "http://127.0.0.1:8091"  # 支付重定向域名
